---
name: Semi-Annual User Access Rights Review
description: Track and document the semi-annual user access rights review process
title: '[Access-Review]: User Access Rights Review - [MONTH]/[YEAR]'
labels: soc, cg:access-control
assignees: AnjaGer
body: |
  # Process
  * @AnjaGer provides the current google workspace user list (SSO provider)
  * @AnjaGer checks this list for consistency and if there is no finding shares it below
  * Review the users/accounts in the tool of your responsibility
  * If there are no findings, check the box below
  * If there **are** findings, please write a comment with the changes/additions/removals you have done to this issue. Check the box below only afterwards.

  # Review Tasks (Tools)
  - [ ] Google Workspace @AnjaGer
  - [ ] Slack @AnjaGer
  - [ ] Github @AnjaGer
  - [ ] Carta @AnjaGer / @sandeep-chopra
  - [ ] MS Office @sandeep-chopra
  - [ ] Zoom @sandeep-chopra
  - [ ] Dropbox @sandeep-chopra
  - [ ] Figma @dcookdesign

  # Review Input
  User List from Google Workspace: [User List](https://docs.google.com/spreadsheets/d/1378wKfJbck7imB1OWbFmxA9GQvJmNy5mARYoOoZyjNU/edit?usp=sharing)
---
