name: Semi Anually User Access Rights Review
description: Track and document the quarterly user access rights review process
labels: "soc, cg:access-control"
assignees: AnjaGer
title: "[Access-Review]: User Access Rights Review - [MONTH]/[YEAR]"
body:
  - type: markdown
    attributes:
      value: |
        ## Review Overview & Process
        User access rights must be reviewed at semi-annually to ensure they remain appropriate.
        This issue tracks the semi-annually effort of reviewing the access rights of tool specific accounts/members and initiating any necessary changes.
        
        - @AnjaGer provides the current google workspace user list (SSO provider)
        - @AnjaGer checks this list for consistency and if there is no finding shares it below       
        - Review the users/accounts in the tool of your responsibility 
        - **If there are no findings**
           - check the box below
        - **If there ARE findings**
           - please write a comment with the changes/additions/removals you have done to this issue
           - **then only check the box below**
        

  - type: textarea
    attributes:
      label: Enter Review Input
      value: |
       > User List from Google Workspace: <ADD GOOGLE DRIVE LINK>

  - type: markdown
    id: review-tasks
    attributes:
      value: |
        ## Review Tasks (Tools) 
        - [ ] Google Workspace @AnjaGer
        - [ ] Slack @AnjaGer
        - [ ] Github @AnjaGer
        - [ ] Carta @AnjaGer / @sandeep-chopra
        - [ ] MS Office @sandeep-chopra
        - [ ] Zoom @sandeep-chopra
        - [ ] Dropbox @sandeep-chopra
        - [ ] Firma @dcookdesign
        - [ ] Grafana, AWS Console @everestsystems/infra (only SSO) 
